/* SPDX-FileCopyrightText: (C) 2026 Gavin John
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * cksum(1p): "The cksum utility shall calculate and write to standard
 * output a cyclic redundancy check (CRC) for the concatenation of all
 * files specified as file operands, using a common algorithm ... in
 * order to allow a system to reliably check whether or not a given
 * arbitrary file has been corrupted."
 *
 * ---- The algorithm, taken from cksum(1p)'s own worked description ------
 *
 * The standard specifies the CRC used here as the one generated by the
 * polynomial
 *   x^32+x^26+x^23+x^22+x^16+x^12+x^11+x^10+x^8+x^7+x^5+x^4+x^2+x^1+x^0
 * (0x04C11DB7, MSB-first / non-reflected) with these exact steps, applied
 * to the concatenation of the file's own bytes followed by its length
 * encoded a byte at a time, least-significant byte first, stopping once
 * the remaining length is zero -- *not* to the file's bytes alone:
 *
 *   1. crc = 0.
 *   2. For each byte c of the file, crc = (crc << 8) ^
 *      table[((crc >> 24) ^ c) & 0xff].
 *   3. Do the same once more for each byte of the file's own length (a
 *      variable number of low-order-byte-first iterations: `for (len;
 *      len != 0; len >>= 8) crc = (crc<<8) ^ table[((crc>>24)^(len&0xff))
 *      & 0xff];` -- so a zero-length file contributes nothing here, and a
 *      length that does not fit in the crc's own byte-at-a-time loop
 *      still terminates because len eventually reaches 0 by repeated
 *      right shift).
 *   4. The result is ~crc (one's complement of the accumulated value).
 *
 * `table` is the standard CRC-32 table generated by the ordinary
 * bit-at-a-time MSB-first method (see gen_table() below) -- crucially
 * NOT the same table zlib/gzip's CRC-32 uses, which reflects both the
 * polynomial and the input/output bits and initializes/finalizes
 * differently.  A implementation that reused zlib's crc32() here would
 * produce a different, silently-wrong number for every input.  This is
 * checked against real reference values from a real `cksum(1)` in
 * test/util-datacopy.c (empty input must checksum to 4294967295, cksum's
 * own well-known fixed point for a zero-length file, plus reference
 * values computed from a real coreutils cksum for a few short strings)
 * rather than trusted on the algorithm description alone.
 *
 * STDOUT: "%d %d %s\n", <checksum>, <total bytes>, <pathname> when a file
 * operand was given; with no file operand (stdin), the pathname column is
 * omitted entirely ("%d %d\n") -- there is no name to report.
 *
 * EXIT STATUS: "0 Successful completion. >0 An error occurred." --
 * diagnose-and-continue across multiple operands, same shape as this
 * project's other utilities: one unreadable file does not stop the rest
 * from being checksummed.
 */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdint.h>
#include "util.h"
#include "ownership_stubs.h"

#define POLY 0x04c11db7UL

/* Built once per process, on first use -- cksum(1p) is never called with
 * zero file operands *and* zero stdin bytes to checksum in the same
 * process twice in a way that would make a static table a hazard, and
 * this process is single-threaded per src/util/test.c's own reasoning
 * about file-scope state in a one-invocation-per-process utility. */
static uint32_t crctab[256];
static int crctab_ready;

static void gen_table(void)
{
	int i, j;
	for (i = 0; i < 256; i++) {
		uint32_t crc = (uint32_t)i << 24;
		for (j = 0; j < 8; j++)
			crc = (crc & 0x80000000UL) ? (crc << 1) ^ POLY : crc << 1;
		crctab[i] = crc;
	}
	crctab_ready = 1;
}

static uint32_t crc_byte(uint32_t crc, unsigned char c)
{
	return (crc << 8) ^ crctab[((crc >> 24) ^ c) & 0xff];
}

/* Reads all of `f`, folding every byte into *crc and *len as it goes.
 * Returns 0 on a clean EOF, -1 on a read error (errno set by fread's
 * underlying stdio, ferror() distinguishes the two). */
static int cksum_stream(FILE *f, uint32_t *crc, uintmax_t *len)
{
	unsigned char buf[8192];
	size_t n;

	while ((n = fread(buf, 1, sizeof buf, f)) > 0) {
		size_t i;
		for (i = 0; i < n; i++) *crc = crc_byte(*crc, buf[i]);
		*len += n;
	}
	return ferror(f) ? -1 : 0;
}

static int cksum_one(const char *path, uint32_t *out_crc, uintmax_t *out_len)
{
	uint32_t crc = 0;
	uintmax_t len = 0;
	uintmax_t l;
	FILE *f;
	int r;

	if (path) {
		/* path, when non-NULL, is always one of __util_cksum_main's own
		 * argv elements -- genuinely null-terminated, but that fact does
		 * not survive across cksum_one's own unannotated parameter. */
		__ownership_string_terminated(path);
		f = fopen(path, "rb");
		if (!f) {
			int saved = errno;
			__util_diagf("cksum: %s: %s\n", path, strerror(saved));
			return -1;
		}
	} else {
		f = stdin;
	}

	r = cksum_stream(f, &crc, &len);
	if (r < 0) {
		int saved = errno ? errno : EIO;
		/* The read failure is primary; closing the input is cleanup only. */
		if (path) (void)fclose(f);
		errno = saved;
		__util_diagf("cksum: %s: %s\n", path ? path : "stdin", strerror(errno));
		return -1;
	}
	if (path && fclose(f) != 0) {
		__util_diagf("cksum: %s: %s\n", path, strerror(errno));
		return -1;
	}

	/* Step 3 above: the length itself, byte by byte, least-significant
	 * first, until nothing remains. */
	for (l = len; l > 0; l /= 256)
		crc = crc_byte(crc, (unsigned char)(l & 0xff));

	*out_crc = ~crc;
	*out_len = len;
	return 0;
}

int __util_cksum_main(
	int argc, char **argv elements_withtok(null_terminated, argc))
{
	int i, had_error = 0;

	if (!crctab_ready) gen_table();

	if (argc < 2) {
		uint32_t crc;
		uintmax_t len;
		if (cksum_one(0, &crc, &len) < 0) return 1;
		printf("%lu %ju\n", (unsigned long)crc, (uintmax_t)len);
		return 0;
	}

	for (i = 1; i < argc; i++) {
		uint32_t crc;
		uintmax_t len;
		char *arg = argv[i];
		const char *path;

		/* arg is one of argv's own elements, genuinely null-terminated
		 * by this function's own elements_withtok(null_terminated, argc)
		 * contract on argv -- restated here since that token does not
		 * survive the argv[i] use inline below this checker can trace on
		 * its own. */
		__ownership_string_terminated(arg);
		/* A lone "-" conventionally means stdin, matching this
		 * project's other utilities (see pathchk.c's own comment on
		 * the same convention). */
		path = strcmp(arg, "-") == 0 ? 0 : arg;

		if (cksum_one(path, &crc, &len) < 0) { had_error = 1; continue; }
		if (path) printf("%lu %ju %s\n", (unsigned long)crc, (uintmax_t)len, path);
		else printf("%lu %ju\n", (unsigned long)crc, (uintmax_t)len);
	}

	return had_error ? 1 : 0;
}
