/* C library headers must use the implementation-reserved namespace for guards,
 * type plumbing, and implementation extensions so they cannot collide with users.
 */
// NOLINTBEGIN(bugprone-reserved-identifier,cert-dcl37-c,cert-dcl51-cpp)

/* SPDX-FileCopyrightText: (C) 2026 Gavin John
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 * <wctype.h>.
 *
 * spicule is C/POSIX-locale-only, and wchar_t here is a 16-bit UTF-16 code
 * unit (WCHAR_MAX == 0xffff, see wchar.h), not the 32-bit-holds-one-
 * codepoint type POSIX text elsewhere implicitly assumes.
 *
 * Classification and case mapping ARE real Unicode, not ASCII-only:
 * isw*()/tow*() answer from real Unicode Character Database data
 * (General_Category, the derived properties, and simple case mapping
 * fields), generated by tools/gen-unicode-tables.py and covering
 * U+0000-U+FFFF, the entire domain a single wchar_t can name here.
 * towupper()/towlower() use only *simple* (1:1, locale-blind) case
 * mappings, the POSIX-mandatory bar: a code point with no simple mapping
 * (e.g. German sharp s, which folds one-to-many) is returned unchanged,
 * the correct conforming answer, not a gap. ctype.h's isalpha() et al.
 * deliberately stay ASCII-only instead, for the separate reason given in
 * that header's own comment; the two families are not meant to agree
 * past 0x7f.
 *
 * A lone surrogate half (0xd800-0xdfff) is not a valid character and its
 * behavior is POSIX-undefined; spicule picks a defined answer anyway:
 * every classification function returns false and every conversion
 * function returns the argument unchanged, since a surrogate half is
 * General_Category Cs and simply absent from every Unicode property
 * these functions consult.
 */

#ifndef _WCTYPE_H
#define _WCTYPE_H

#include <features.h>
#include <string_tokens.h>

#define __NEED_wint_t
#define __NEED_wctype_t

/* POSIX requires locale_t here unconditionally, matching ctype.h. */
#define __NEED_locale_t

#include <bits/alltypes.h>

#ifdef __cplusplus
extern "C" {
#endif

#undef WEOF
#define WEOF 0xffffffffU

/* spicule's one locale defines exactly two mappings ("tolower", "toupper"),
 * so a small dense int enum is all the opacity this type needs. */
typedef int wctrans_t;

int iswalnum(wint_t) __attribute__((__pure__));
int iswalpha(wint_t) __attribute__((__pure__));
int iswblank(wint_t) __attribute__((__pure__));
int iswcntrl(wint_t) __attribute__((__pure__));
int iswdigit(wint_t) __attribute__((__pure__));
int iswgraph(wint_t) __attribute__((__pure__));
int iswlower(wint_t) __attribute__((__pure__));
int iswprint(wint_t) __attribute__((__pure__));
int iswpunct(wint_t) __attribute__((__pure__));
int iswspace(wint_t) __attribute__((__pure__));
int iswupper(wint_t) __attribute__((__pure__));
int iswxdigit(wint_t) __attribute__((__pure__));

/* Same equivalence as ctype.h's isalnum_l() family: each iswXXX_l() is
 * its non-_l sibling above, taking and ignoring a locale_t. */
int iswalnum_l(wint_t, locale_t) __attribute__((__pure__));
int iswalpha_l(wint_t, locale_t) __attribute__((__pure__));
int iswblank_l(wint_t, locale_t) __attribute__((__pure__));
int iswcntrl_l(wint_t, locale_t) __attribute__((__pure__));
int iswdigit_l(wint_t, locale_t) __attribute__((__pure__));
int iswgraph_l(wint_t, locale_t) __attribute__((__pure__));
int iswlower_l(wint_t, locale_t) __attribute__((__pure__));
int iswprint_l(wint_t, locale_t) __attribute__((__pure__));
int iswpunct_l(wint_t, locale_t) __attribute__((__pure__));
int iswspace_l(wint_t, locale_t) __attribute__((__pure__));
int iswupper_l(wint_t, locale_t) __attribute__((__pure__));
int iswxdigit_l(wint_t, locale_t) __attribute__((__pure__));

int iswctype(wint_t, wctype_t) __attribute__((__pure__));
wctype_t wctype(const char * withtok(null_terminated)) __attribute__((__pure__));

int iswctype_l(wint_t, wctype_t, locale_t) __attribute__((__pure__));
wctype_t wctype_l(const char * withtok(null_terminated), locale_t) __attribute__((__pure__));

wint_t towlower(wint_t) __attribute__((__pure__));
wint_t towupper(wint_t) __attribute__((__pure__));
wint_t towctrans(wint_t, wctrans_t) __attribute__((__pure__));
wctrans_t wctrans(const char * withtok(null_terminated)) __attribute__((__pure__));

wint_t towlower_l(wint_t, locale_t) __attribute__((__pure__));
wint_t towupper_l(wint_t, locale_t) __attribute__((__pure__));
wint_t towctrans_l(wint_t, wctrans_t, locale_t) __attribute__((__pure__));
wctrans_t wctrans_l(const char * withtok(null_terminated), locale_t) __attribute__((__pure__));

#ifdef __cplusplus
}
#endif

#endif

// NOLINTEND(bugprone-reserved-identifier,cert-dcl37-c,cert-dcl51-cpp)
