.\" SPDX-FileCopyrightText: (C) 2026 Gavin John
.\" SPDX-License-Identifier: GPL-3.0-or-later
.TH FALSE 1 "2026" "spicule" "spicule User Commands"
.SH NAME
false \- do nothing, unsuccessfully
.SH SYNOPSIS
.B false
.RI [ operand ] .\|.\|.
.SH DESCRIPTION
.B false
exits with a return status that indicates unsuccessful completion. It
can be invoked with any combination of options and operands; all are
ignored.
.SH OPTIONS
None.
.SH OPERANDS
None; any operands given are ignored without error.
.SH EXIT STATUS
.TP
.B 1
Always.
.SH SEE ALSO
.BR true (1),
.BR test (1)
